postgres:
  image: postgres:9.3
  environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=12345678
    - POSTGRES_DB=dbname

unnamed-startup:
  image: benoc008/minglefield
  links:
    - postgres
  ports:
    - 8080:8080
    - 5005:5005